spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/buzzdb
spring.datasource.username=postgres
spring.datasource.password=Mybday_28
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

jwt.secret=BuzzApp2026SecretKeyForCodeQuestKNUST
jwt.expiration=86400000