spring.application.name=attendance-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/buzzdb
spring.datasource.username=postgres
spring.datasource.password=Mybday_28

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

auth.service.url=http://localhost:8081
attendance.arrival.cutoff=08:00
