spring.application.name=safety-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/buzzdb
spring.datasource.username=postgres
spring.datasource.password=Mybday28
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

auth.service.url=http://localhost:8081